# Generated by Django 5.1.5 on 2025-01-27 16:38

import django.db.models.deletion
import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Juego')),
                ('category', models.CharField(default='General', max_length=50, verbose_name='Categoría')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('code', models.CharField(default=games.models.generate_unique_code, max_length=5, unique=True, verbose_name='Código Único')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
