# Generated by Django 5.2a1 on 2025-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Código Único'),
        ),
    ]
